apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: k-s
build:
  artifacts:
    - image: matan/my-app
deploy:
  helm:
    releases:
      - name: skaffold-helm
        chartPath: ./charts/backend
        valuesFiles:
          - charts/backend/templates/.spec.values.yaml
        values:
          image: matan/my-app
