apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: matan/node-web-app
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
          # Inside the container
          volumeMounts:
            - mountPath: /usr/src/app/src
              name: test-volume
      volumes:
        - name: test-volume
          # on my machine
          hostPath:
            path: /Users/matan.c/dev/play/k8s/src
                
---
apiVersion: v1
kind: Service
metadata:
  name: knote
spec:
  selector:
    app: knote
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer