apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: app
          image: {{.Values.image }}
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-configmap
          ports:
            - containerPort: 3000
          
         
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 4000
      targetPort: 3000
  type: LoadBalancer
