apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: app
          image: {{.Values.image }}
          imagePullPolicy: {{.Values.pullPolicy }}
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-configmap
          ports:
            - containerPort: {{ .Values.nodePort }}
         

