{{- if .Values.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.canary.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
    version: {{ .Values.canary.version }}
spec:
  replicas: {{ .Values.canary.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
        version: {{ .Values.canary.version }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: {{.Values.canary.image }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
            - secretRef:
                name: {{ .Values.secrets.name }}
          ports:
            - containerPort: {{ .Values.nodePort }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.serviceName }}
spec:
  host: {{ .Values.serviceName }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: {{ .Values.deployment.version }}
    labels:
      version: {{ .Values.deployment.version }}
  - name: {{ .Values.canary.version }}
    labels:
      version: {{ .Values.canary.version }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{.Values.serviceName }}
spec:
  gateways:
    - {{ .Values.namespace.name }}-gateway
  hosts:
    - {{ .Values.viratulService.host }}
  http:
  - route:
    - destination:
        host: {{.Values.serviceName }}
        subset: v1
      weight: 70
    - destination:
        host: {{.Values.serviceName }}
        subset: v2
      weight: 30      
{{- end }}
