apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.configMap.name }}
data:
{{- range $key, $val := .Values.envs }}
  {{ $key | upper }}: {{ $val | quote }}
{{- end }}