
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.secrets.name }}
data:
{{- range $key, $val := .Values.values }}
  {{ $key | upper }}: {{ $val | b64enc | quote }}
{{- end }}