apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
    service: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - port: {{ .Values.nodePort }}
      name: http
      targetPort: {{ .Values.nodePort }}

