{{- if eq .Values.canary.enabled false }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace.name }}
spec:
  gateways:
    - {{ .Values.namespace.name }}-gateway
  hosts:
    - {{ .Values.viratulService.host }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{.Values.serviceName }}
{{- end }}
